import NavbarWithSimpleLinks from "./components/NavBar";
import "./globals.css";
import ReactToast from "./utils/ReactToast";
import { getServerSession } from "next-auth";
import AuthProvider from "./utils/SessionProvider";

export const metadata = {
  title: "Best Villa in the World",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className="font-serif">
        <AuthProvider session={session}>
          <NavbarWithSimpleLinks />
          {children}
          <ReactToast />
        </AuthProvider>
      </body>
    </html>
  );
}
